service: bikair-payment-methods
useDotenv: true
frameworkVersion: '3'
plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
  - serverless-plugin-aws-alerts
  - serverless-offline
custom:
  stage: ${opt:stage, 'develop'}
  prune:
    automatic: true
    number: 1
  alerts:
    stages:
      - production
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: dev-alerts@bik-air.com
    alarms:
      - functionErrors
provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-3
  memorySize: 400
  timeout: 29
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MICROSERVICE_NOTIFICATION: ${env:MICROSERVICE_NOTIFICATION}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_TAX_RATES: ${env:STRIPE_TAX_RATES}
  iam:
    role:
      statements:
        - ${file(../../serverless.common.yml):logGroupPolicy}
        - ${file(../../serverless.common.yml):secretPolicy}
        - ${file(../../serverless.common.yml):invokeNotificationPolicy}
  vpc: ${file(../../serverless.common.yml):vpc}
  httpApi: ${file(../../serverless.common.yml):httpApiConfig}
functions:
  get-payment-methods:
    handler: src/functions/get-payment-methods.handler
    events:
      - httpApi:
          path: /
          method: GET
          authorizer:
            name: tokenClientAuthorizer
  post-payment-methods:
    handler: src/functions/post-payment-methods.handler
    events:
      - httpApi:
          path: /
          method: POST
          authorizer:
            name: tokenClientAuthorizer
  get-payment-methods-secret:
    handler: src/functions/get-payment-methods-secret.handler
    events:
      - httpApi:
          path: /secret
          method: GET
          authorizer:
            name: tokenClientAuthorizer
  get-payment-sheet:
    handler: src/functions/post-payment-sheet.handler
    events:
      - httpApi:
          path: /sheet
          method: POST
          authorizer:
            name: tokenClientAuthorizer
